### PR TITLE
logseq graph analysis

### PR DESCRIPTION
**Pull request by trashhalo**
# Submit a new Plugin to Marketplace

Plugin Github repo URL: https://github.com/trashhalo/logseq-graph-analysis

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by cnrpman** [comment]
I love it! ❤️

**Comment by sawhney17** [comment]
Great Plugin!

A few change to be requested, in the original repo's package.json, the ID field is set to Logseq summarizer. 

Also, the toolbar has the key "logseq-sticky-notes" which I don't think is intentional 

I also believe that you should probably add an x button or maybe have it render in the main content area with the exception of the top bar and the sidebar. I myself struggled to figure out I had to press escape to come out of the view. 

Absolutely love the plugin nonetheless!

**Review by sawhney17 — CHANGES_REQUESTED** [review]
A few change to be requested, in the original repo's package.json, the ID field is set to Logseq summarizer.

Also, the toolbar has the key "logseq-sticky-notes" which I don't think is intentional

I also believe that you should probably add an x button or maybe have it render in the main content area with the exception of the top bar and the sidebar. I myself struggled to figure out I had to press escape to come out of the view.

Absolutely love the plugin nonetheless!

**Comment by trashhalo** [comment]
updated with requested changes. Close button looks like this
closebutton

**Comment by sawhney17** [comment]
Looks good. Just one issue left. The id field in package.json is still showing logseq summarizer. Just update that an we should be good to merge

**Comment by trashhalo** [comment]
> Looks good. Just one issue left. The id field in package.json is still showing logseq summarizer. Just update that an we should be good to merge

Oops totally failed at pushing the code correctly all the pieces should be there and included in version 0.0.5

**Comment by sawhney17** [comment]
Awesome. Merging

**Pull request merged**
