### PR TITLE
added ai query generator plugin

### PR DESCRIPTION
**Pull request by dailydaniel**
# Submit a new Plugin to Marketplace

https://github.com/dailydaniel/logseq-plugin-ai-query

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (theme plugin for [this](https://github.com/Sansui233/logseq-bonofix-theme/blob/master/.github/workflows/publish.yml)).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @dailydaniel I just found that the entry file path is incorrect from the bundled plugin package.

ref link: https://github.com/dailydaniel/logseq-plugin-ai-query/blob/main/.github/workflows/publish.yaml#L30

CleanShot 2024-08-31 at 10 23 29@2x

**Comment by dailydaniel** [comment]
Hi, @xyhp915 
i've fixed everything and made new release, sorry)

**Comment by dailydaniel** [comment]
checked v0.1.8 release zip in dev mode, it works

**Comment by dailydaniel** [comment]
Hi, @xyhp915 
Do i need to make a new pull request after fixing all problems?

**Pull request merged**
