### PR TITLE
Adding Arxiv mate plugin manifest

### PR DESCRIPTION
**Pull request by SSamDav**
# Submit a new Plugin to Marketplace

**Plugin Github repo URL:**  

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (theme plugin for [this](https://github.com/Sansui233/logseq-bonofix-theme/blob/master/.github/workflows/publish.yml)).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by SSamDav** [comment]
Fist time doing a plugin in json, so I don't know if my CI workflow was correctly set up 😅

**Comment by xyhp915** [comment]
> Fist time doing a plugin in json, so I don't know if my CI workflow was correctly set up 😅

Cool. Also, you should create a new release (tag) to trigger CI for the Marketplace zip package :)



Your plugin releases list: https://github.com/SSamDav/logseq-logarxivmate-plugin/releases

**Comment by SSamDav** [comment]
> Cool. Also, you should create a new release (tag) to trigger CI for the Marketplace zip package :)

@xyhp915 I just created a new release, how can I see if everything worked fine?

**Comment by xyhp915** [comment]
Hi @SSamDav I just found an error in the build workflow. https://github.com/SSamDav/logseq-logarxivmate-plugin/actions/runs/9267108511/job/25492803359

A helpful link for it : https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac

**Comment by SSamDav** [comment]
> A helpful link for it : https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac

@xyhp915 Followed the answer and it seems that it fixed the builds error! Thanks!

**Pull request merged**
