### PR TITLE
New `logseq13-full-house-plugin`

### PR DESCRIPTION
**Pull request by stdword**
# Submit a new Plugin to Marketplace

Plugin Github repo URL: https://github.com/stdword/logseq13-full-house-plugin

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @stdword, Great works! I found the GitHub CI of this plugin did not build the zip package for the Marketplace repo. You can refer to this workflow: https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10

CleanShot 2023-03-06 at 10 07 23@2x

**Comment by stdword** [comment]
Fixed! Thank you!)

**Comment by xyhp915** [comment]
> @xyhp915 Fixed! Thank you!)

Cool! But I found the plugin entry file path is incorrect. Also, the metafile `package.json` should be placed in the root directory.

CleanShot 2023-03-06 at 14 51 01@2x

**Comment by stdword** [comment]
@xyhp915 Fixed again!)

**Pull request merged**
