### PR TITLE
adds logseq-matter to packages

### PR DESCRIPTION
**Pull request by hunterclarke**
# Submit a new Plugin to Marketplace

Plugin Github repo URL: https://github.com/getmatterapp/logseq-matter

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @hunterclarke, I found the repo [logseq-matter](https://github.com/getmatterapp/logseq-matter) is not public.

**Comment by hunterclarke** [comment]
Sorry about that! Updated @xyhp915

**Comment by xyhp915** [comment]
@hunterclarke Such a cool plugin for the Matter app. A small polish PR for better :) https://github.com/getmatterapp/logseq-matter/pull/1

**Comment by hunterclarke** [comment]
Nice spot! Updated and included in v1.0.1

**Pull request merged**
