### PR TITLE
Highlighters plugin

### PR DESCRIPTION
**Pull request by DenaroCF**
# Submit a new Plugin to Marketplace

Plugin Github repo URL: [Highlighters for Logseq by Denaro](https://github.com/DenaroCF/Highlighters-for-Logseq)

## Github releases checklist

- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) action for Github releases. (Optional for theme plugin only)
- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a clear README file.
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by tiensonqin** [comment]
@DenaroCF Nice plugin! 
It seems that a license is not included.

**Comment by DenaroCF** [comment]
@tiensonqin License added ;)

**Comment by xyhp915** [comment]
@DenaroCF Ping me anytime for CI workflow of Github action if you need help :)

**Comment by DenaroCF** [comment]
@xyhp915 Done! :)

**Comment by xyhp915** [comment]
> @xyhp915 Done! :)

Cool. I tried but the release zip package is not found here. https://github.com/DenaroCF/Highlighters-for-Logseq/releases
Could you try to create a version-related tag manually, then push tags `git push origin --tags` to trigger Github workflow.

**Comment by ahangarha** [comment]
Since there is no progress in the repo, I propose closing this PR.

**Pull request closed without merging**
