### PR TITLE
Adding plugin request for logseq-todoist-plugin

### PR DESCRIPTION
**Pull request by hkgnp**
# Submit a new Plugin to Marketplace

Plugin Github repo URL:

## Github releases checklist

- [ ] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) action for Github releases. (Optional for theme plugin only)
- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a clear README file.
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @hkgnp I found the release's package.json entry is incorrect.
A1C05078-4ED9-496D-B662-5ED3679D948F

**Comment by hkgnp** [comment]
Hi @xyhp915. thanks for the comment! made the necessary changes.
Hope it's ok now!

**Comment by xyhp915** [comment]
> Hi @xyhp915. thanks for the comment! made the necessary changes. Hope it's ok now!
> 
> Edit: Actually perhaps I should clarify. When a plugin is installed on Logseq, is npm run build" being run on the system or are the files merely copied over?
> 
> If "npm run build" is being run, then dist/index.html will be correct because parcel builds to that directory and will become the entry point to the program.

The Github release zip package will be downloaded via installation from Marketplace. So we should pack all build files into the zip package by CI workflow or manually. Hope this link is helpful https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L47

E6F37304-83F4-47DB-AA36-861B95A95842

**Comment by hkgnp** [comment]
Thanks! Yes it is indeed helpful. I've decided to do the manual way as I'm not too familiar with Github actions yet.

Please see if it's ok. Sorry again for the trouble!

**Pull request merged**
