### PR TITLE
Add logseq-save-scrollbar-position

### PR DESCRIPTION
**Pull request by studyduck**
# Submit a new Plugin to Marketplace

Plugin Github repo URL: https://github.com/studyduck/logseq-save-scrollbar-position

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @studyduck I found this plugin missing a release zip pkg from the Github releases list. Give you some helpful links below :)
https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10 
https://github.com/xyhp915/logseq-journals-calendar/releases

**Comment by studyduck** [comment]
> Hi @studyduck I found this plugin missing a release zip pkg from the Github releases list. Give you some helpful links below :)
> 
> * https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10
> * https://github.com/xyhp915/logseq-journals-calendar/releases

This plugin only has an index.js, it doesn't need to be built, do I also need to add a .github/workflows/publish.yml file

**Comment by xyhp915** [comment]
> > Hi @studyduck I found this plugin missing a release zip pkg from the Github releases list. Give you some helpful links below :)
> > 
> > * https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10
> > * https://github.com/xyhp915/logseq-journals-calendar/releases
> 
> This plugin only has an index.js, it doesn't need to be built, do I also need to add a .github/workflows/publish.yml file. And i have just added a release zip package

Yes. That's required. You can checkout this plugin :) https://github.com/cannibalox/logtools

**Comment by studyduck** [comment]
> 

thanks, i have added a publish.yml file

**Comment by heimi98** [comment]
I want this plugin for a long time. Thank you!

**Comment by studyduck** [comment]
> I want this plugin for a long time. Thank you!

Thanks for letting me know about this. Whether I use logseq or other note-taking software such as roam research, I feel this should be a built-in feature, but unfortunately none of these have it, so I wrote this plugin with my limited programming skill.

**Pull request merged**
