### PR TITLE
Add logseq-blocknav

### PR DESCRIPTION
**Pull request by KerfuffleV2**
# Submit a new Plugin to Marketplace

Plugin Github repo URL: https://github.com/KerfuffleV2/logseq-plugin-blocknav

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by KerfuffleV2** [comment]
There's no animated GIF, so sue me! There really wouldn't be anything to see with the functionality this plugin provides.

I don't really know how to verify that the built version of the plugin actually functions properly. Extracting it into `~/.logseq/plugins/` doesn't seem to work. It can successfully be loaded as unpacked.

**Comment by xyhp915** [comment]
> There's no animated GIF, so sue me! There really wouldn't be anything to see with the functionality this plugin provides.
> 
> I don't really know how to verify that the built version of the plugin actually functions properly. Extracting it into `~/.logseq/plugins/` doesn't seem to work. It can successfully be loaded as unpacked.

Cool plugin! I tried it in marketplace mode that works well.

**Comment by KerfuffleV2** [comment]
@xyhp915 Thanks for approving this, but it doesn't seem to work at all for me when loading from the marketplace. You were actually able to use the shortcuts and view the settings page? It doesn't appear that it's even loading the main `index.js` file.

I finally got it to load by manually messing with the plugin directory and copying in an `index.html` and setting the `main` key in `package.json` to point at that but according to the document you wrote, using a JS file should be okay: https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69 And it did work without the iframe approach in unpacked mode so I am confused. I'm using Logseq 0.7.0.

Do I need to just use a HTML main or is there something else I should be doing to fix this? (Hopefully it's okay to ask you these questions here!)

**Comment by xyhp915** [comment]
Yes. It works well via installation from the marketplace.

And I found you change SDK resource url to remote. 
```html
<script src="https://cdn.jsdelivr.net/npm/@logseq/libs@0.0.6"></script>
```
If so, the plugin will not be available when the network is offline.

Or why not use build a tool like `parcel`, `vite`, etc. Those so simple.

here some helpful links:
https://parceljs.org/getting-started/webapp/
https://vitejs.dev/guide/
https://github.com/logseq/logseq-plugin-samples/tree/master/logseq-a-translator
https://github.com/xyhp915/logseq-journals-calendar

**Comment by KerfuffleV2** [comment]
@xyhp915 Thanks for the reply.

> It works well via installation from the marketplace.

The current version does work, because I changed to using the iframe approach rather than just having `"main": "index.js"` in `package.json`. The one that had the issue was `v0.0.3` I believe.

Is setting the `main` key directly to a JavaScript file not actually supposed to work?

> And I found you change SDK resource url to remote.

If you're talking about the current version, the build script (which is run by the GitHub action) fixes up the URI and ensures there's a local copy of the API. The version I was talking about didn't have an `index.html` at all: at that point, the build script was just downloading the API and concatenating it with the source. Ref: https://github.com/KerfuffleV2/logseq-plugin-blocknav/blob/v0.0.3/build.sh

> Or why not use build a tool like parcel, vite, etc. Those so simple.

I'm doing basically the same thing in the GitHub action. Just wanted to avoid requiring extra stuff since this _only_ depends on the Logseq API.

**Pull request merged**
