### PR TITLE
Add logseq-chinese-tools

### PR DESCRIPTION
**Pull request by piobmx**
# Submit a new Plugin to Marketplace

Plugin Github repo URL:

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @piobmx I found the current release (`0.0.1`) is `pre-release` status. I think it should be adjusted for this service  https://api.github.com/repos/piobmx/logseq-chinese-tools/releases/latest

**Comment by vipzhicheng** [comment]
@xyhp915 I want to know after a code like this merged when it can take effect to Logseq users.

**Comment by xyhp915** [comment]
> @xyhp915 I want to know after a code like this merged when it can take effect to Logseq users.

There is a private API available for temporary use by administrators. 
```js
// run in console in host
logseq.api.__install_plugin({id:"logseq-chinese-tools", repo: "piobmx/logseq-chinese-tools", theme: false, effect: false})
```
However, it is intended to expose this functionality to users as `install from Github` in the future.

**Comment by vipzhicheng** [comment]
> > @xyhp915 I want to know after a code like this merged when it can take effect to Logseq users.
> 
> There is a private API available for temporary use by administrators.
> 
> ```js
> // run in console in host
> logseq.api.__install_plugin({id:"logseq-chinese-tools", repo: "piobmx/logseq-chinese-tools", theme: false, effect: false})
> ```
> 
> However, it is intended to expose this functionality to users as `install from Github` in the future.

Sorry for commenting at the wrong issue. I still do not know when users can feel "bug" fixed after you merged my `effect: true`. 

BTW, your advice works.

**Comment by piobmx** [comment]
> Hi @piobmx I found the current [release](https://github.com/piobmx/logseq-chinese-tools/releases/tag/v0.0.1) (`0.0.1`) is `pre-release` status. I think it should be adjusted for this service https://api.github.com/repos/piobmx/logseq-chinese-tools/releases/latest

Hi, I've uploaded a new version. Please check that out and let me know if there are any issues.

**Pull request merged**
