### PR TITLE
change author

### PR DESCRIPTION
**Pull request by mlanza**
# Submit a new Plugin to Marketplace

Modify author to overcome installation issue.  I was unable to install the plugin from the marketplace although I can install it just fine using the "Load unpacked plugin" procedure.  In looking at other plugin manifests, I assume the author being my full name (rather than user name) was the issue.

I keep getting an "[Install Error]:release-asset-not-found" when attempting an install.  Hopefully my fixing the author inconsistency will solve the issue.

Same as mentioned here:
https://github.com/logseq/logseq/issues/3365

### CODE REVIEW

**Comment by mlanza** [comment]
@sawhney17 — I've never used a release workflow.  Was this documented in the plugin release process?  I reviewed all the plugin authoring documentation I was aware of.  Could you please point me to where this step is described?  My apologies.

**Comment by sawhney17** [comment]
Isn't described anywhere really but this forum post should help. 

https://forum.obsidian.md/t/using-github-actions-to-release-plugins/7877

In my session on plug-in development tomorrow, I'll be walking through the entire process and will cover it there and provide a template. You can wait till then if you can't figure it out from the forum post.

**Comment by xyhp915** [comment]
> @sawhney17 — I've never used a release workflow. Was this documented in the plugin release process? I reviewed all the plugin authoring documentation I was aware of. Could you please point me to where this step is described? My apologies.

Hi @mlanza A related PR for this issue https://github.com/mlanza/logseq-wide-eyed/pull/1

**Comment by mlanza** [comment]
@xyhp915 — thanks for the pull request.  I pulled it.  I still haven't had the time to properly learn Github Actions.

I wasn't sure why the html file was added back (in the pull) since my plugin has no main UI.  I dropped it recently. I thought I read somewhere that the html file could be omitted if your plugin has no main UI.  And when I tested it locally with just the index.js it worked fine.

I still don't appear to be able to install from the marketplace so I'm sure I'll need to read up and figure out what else has to happen.  But thanks for the help.

**Comment by xyhp915** [comment]
> I thought I read somewhere that the html file could be omitted if your plugin has no main UI.
@mlanza Yes. That's OK. But I found there's a bug if `index.js` as the entry with marketplace package. You could adjust it when the bug is fixed in the next release.

**Comment by sawhney17** [comment]
now that you’ve got the release workflow, you actualyl have to trigger the release. First pull changes from github to your local IDE. Then do `cd repo-name, unless you’re using the integrated terminal in VSC already` and then run `git tag 1.0.0`. Finally run `git push origin —tags` to start the process. In the actions tab on your github page you will be able to see the process.

**Comment by mlanza** [comment]
@sawhney17 — I believe I accomplished the same thing, making a release, using the the Github UI.  Next time I will try the workflow you suggest, but I already see the release I created on my repo.

**Pull request merged**
