### PR TITLE
add logseq-task-done-time-mini plugin package

### PR DESCRIPTION
**Pull request by mlhiter**
# Submit a new Plugin to Marketplace

**Plugin Github repo URL:**  https://github.com/mlhiter/logseq-task-done-time-mini

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (theme plugin for [this](https://github.com/Sansui233/logseq-bonofix-theme/blob/master/.github/workflows/publish.yml)).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @mlhiter Testing that was found the event listened to by `db change` entered into an infinite loop.


https://github.com/user-attachments/assets/aa84cee6-8660-4528-a85b-a9c7bdab75be

**Comment by mlhiter** [comment]
This seems my regexp error，I will fix this error this afternoon.💪

**Comment by mlhiter** [comment]
@xyhp915 I fix this bug just now.😀

**Comment by xyhp915** [comment]
> @xyhp915 I fixed this bug just now.😀

I still have this issue; you can try using the `preferredDate` configuration format as below to reproduce!
CleanShot 2024-08-02 at 15 59 39@2x

BTW, I probably guess it's caused by these two related regular expressions.

CleanShot 2024-08-02 at 16 05 07@2x

Helpful links:
https://github.com/logseq/logseq/blob/7cc0b15d0436d025527cbd9108a5951fef54552f/src/main/frontend/worker/date.cljs#L14

**Comment by mlhiter** [comment]
@xyhp915 Yes,you are right. A comma is always followed by a space and I forgot to modify the value.hh.
And now its no problem : )
v1.1.2 is released.

**Pull request merged**
