### PR TITLE
add logseq-plugin-charspacing

### PR DESCRIPTION
**Pull request by sethyuan**
# Submit a new Plugin to Marketplace

Plugin Github repo URL:

## Github releases checklist

- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) action for Github releases. (Optional for theme plugin only)
- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a clear README file.
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by sethyuan** [comment]
I found a bug affecting page/block references, please **don't merge** this yet. I'll try to make a workaround.

**Comment by xyhp915** [comment]
@sethyuan COOL idea! But A tip below:
I found that there is a certain risk of memory leaks when the plugin is uninstalled or reloaded. https://github.com/sethyuan/logseq-plugin-charspacing/blob/master/public/index.js#L53
You could try to clean some effects by this life hook. https://logseq.github.io/plugins/interfaces/ILSPluginUser.html#beforeunload

**Comment by sethyuan** [comment]
@xyhp915 You're right , will do.

**Comment by sethyuan** [comment]
Due to conflicts with the internal rendering engine on who owns DOM mutations, my original implementation of DOM mutations (inserting new nodes on-the-fly) is not feasible. So I changed the way it is implemented, now it uses mutations on text nodes only.

I've tested it in different places and it seems to work nice now.

**Pull request merged**
