### PR TITLE
Adding logseq-lilypond as a new plugin

### PR DESCRIPTION
**Pull request by Vaults**
# Submit a new Plugin to Marketplace

Plugin Github repo URL: https://github.com/dot-asterisk-nl/logseq-lilypond

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @Vaults A helpful PR is pending https://github.com/dot-asterisk-nl/logseq-lilypond/pull/1

**Comment by Vaults** [comment]
Hi @xyhp915, thanks for helping out :) It's merged!

**Comment by Vaults** [comment]
Is there anything else I need to do?

**Comment by xyhp915** [comment]
> Is there anything else I need to do?

Weirdly, the entry file path is still `index.html`  

CleanShot 2023-03-02 at 22 44 51@2x

Also, I found the latest build CI script is not correct...  

https://github.com/dot-asterisk-nl/logseq-lilypond/actions/runs/4308177998/workflow#L27

**Pull request merged**
