### PR TITLE
feat: add logseq-mind-map plugin

### PR DESCRIPTION
**Pull request by b-yp**
# Submit a new Plugin to Marketplace

**Plugin Github repo URL:**  https://github.com/b-yp/logseq-mind-map
## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (theme plugin for [this](https://github.com/Sansui233/logseq-bonofix-theme/blob/master/.github/workflows/publish.yml)).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @b-yp I just found the Gtihub release is missing. https://github.com/b-yp/logseq-mind-map/releases

**Comment by b-yp** [comment]
> Hi @b-yp I just found the Gtihub release is missing. https://github.com/b-yp/logseq-mind-map/releases

I just updated.

**Comment by b-yp** [comment]
@xyhp915     Hello, the Github release was deleted because a dependency had an outdated version, which was detected as a vulnerability by Github. After upgrading the dependency, I repackaged it, and the code was merged. However, why is it still not searchable in Logseq? Is there anything else I need to do?

**Comment by b-yp** [comment]
> @xyhp915 Hello, the Github release was deleted because a dependency had an outdated version, which was detected as a vulnerability by Github. After upgrading the dependency, I repackaged it, and the code was merged. However, why is it still not searchable in Logseq? Is there anything else I need to do?

I just found out it's searchable now, so please disregard this message.

**Pull request merged**
