### PR TITLE
Publish SamePage Extension

### PR DESCRIPTION
**Pull request by dvargas92495**
# Submit a new Plugin to Marketplace

Plugin Github repo URL: https://github.com/samepage-network/logseq-samepage

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

I had a few questions before this is officially ready for review:
- Can the CI workflow be named whatever I want or does it have to be named `publish.yml` ?
- How do you guys handle updates to the plugin? Do I have to submit each update for review or does it automatically update with each release created?
- Is there a way to mark an extension as "in beta" or "early access" or something like that? The family of extensions need a lot more user testing but I want to have it available in each app's store for ease of other users testing

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @dvargas92495 awesome works :)
> Can the CI workflow be named whatever I want or does it have to be named publish.yml ?

This is a GitHub rule, and it seems that you don't have to use this name. For Logseq, it's just a matter of building a usable zip release package, something like:
CleanShot 2022-11-16 at 11 11 52@2x

> How do you guys handle updates to the plugin? Do I have to submit each update for review or does it automatically update with each release created?

You don't have to. If the build CI works, for the updates what you should do is just create a new release.
CleanShot 2022-11-16 at 11 17 31@2x

> Is there a way to mark an extension as "in beta" or "early access" or something like that? The family of extensions need a lot more user testing but I want to have it available in each app's store for ease of other users testing

There are currently no multiple update channels. I think you can clearly put the "Beta or Early access" label after the plugin name, or in the description?

**Comment by dvargas92495** [comment]
Ok great, the latest release should now have the zip. The README currently has a warning for users using the extension - but I just wanted to see if there was a native way to communicate that the extension is in "Beta".

In any case, it's ready for review!

**Comment by xyhp915** [comment]
Hi @dvargas92495  I just found this kind of version name (release tag) is not work for updates. Could you try the semver name for it? https://semver.org/
> PS: The semver name supports pre-release identifiers (alpha, beta...) I thought this might be helpful to you :)

CleanShot 2022-11-17 at 10 52 48@2x

**Comment by dvargas92495** [comment]
Latest version should now be semver compatible

On another note, is there a hosted version of logseq somewhere? I'd like to write some end-to-end tests for the extension, but would like to avoid booting up or hosting a version of the application myself to test against

**Comment by xyhp915** [comment]
> On another note, is there a hosted version of logseq somewhere? I'd like to write some end-to-end tests for the extension, but would like to avoid booting up or hosting a version of the application myself to test against

Cool! Recommend you upgrade `@logseq/libs` to the latest version :). And you can resolve the app version from this API.

CleanShot 2022-11-18 at 11 05 29@2x

**Comment by dvargas92495** [comment]
I meant is there a URL where one could access a web-hosted version of the Logseq app instead of electron, not the version of the logseq library

**Pull request merged**
