### PR TITLE
Tenset security theme

### PR DESCRIPTION
**Pull request by Danila-cloud**
# Submit a new Plugin to Marketplace

Plugin Github repo URL:

## Github releases checklist

- [ ] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [ ] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [ ] a release which includes a release zip pkg from a successful build.
- [ ] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [ ] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @Danila-cloud I found this plugin missing release GitHub action to build a zip package for the Marketplace. You can refer  to this helpful link :)   https://github.com/Sansui233/logseq-bonofix-theme/tree/master/.github/workflows

**Comment by Danila-cloud** [comment]
> Hi @Danila-cloud I found this plugin missing release GitHub action to build a zip package for the Marketplace. You can refer to this helpful link :) https://github.com/Sansui233/logseq-bonofix-theme/tree/master/.github/workflows
Done, can you check if everything is okay?

**Comment by Danila-cloud** [comment]
> Hi @Danila-cloud I found this plugin missing release GitHub action to build a zip package for the Marketplace. You can refer to this helpful link :) https://github.com/Sansui233/logseq-bonofix-theme/tree/master/.github/workflows

Done, can you check if everything is ok?

**Comment by xyhp915** [comment]
> Done, can you check if everything is ok?

Hi @Danila-cloud I found the path of the theme entry file is incorrect from the released package.

CleanShot 2023-08-07 at 10 51 13@2x

**Comment by Danila-cloud** [comment]
> > Done, can you check if everything is ok?
> 
> Hi @Danila-cloud I found the path of the theme entry file is incorrect from the released package.
> 
> CleanShot 2023-08-07 at 10 51 13@2x

Hi @xyhp915 , looks like it is fixed

**Pull request merged**
