### PR TITLE
logseq-query-builder-plugin

### PR DESCRIPTION
**Pull request by adxsoft**
# Submit a new Plugin to Marketplace

Plugin Github repo URL:

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [n/a ] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by adxsoft** [comment]
I notice that you mention adding tags for version numbers. I wasn't sure how to do this. The Version number is 0.4

**Comment by Bad3r** [comment]
Plugin repo: https://github.com/adxsoft/logseqadvancedquerybuilder

**Comment by xyhp915** [comment]
Hi @adxsoft I created a PR to build the Marketplace package.  I hope it's helpful :)
https://github.com/adxsoft/logseq-query-builder-plugin/pull/2

**Comment by adxsoft** [comment]
> Hi @adxsoft I created a PR to build the Marketplace package. I hope it's helpful :) [adxsoft/logseq-query-builder-plugin#2](https://github.com/adxsoft/logseq-query-builder-plugin/pull/2)

Thanks for your help. I believe I've done everything that's needed. Can this pull request get merged now?

**Comment by xyhp915** [comment]
> Thanks for your help. I believe I've done everything that's needed. Can this pull request get merged now?

Cool. Also, you should create a new release (tag) to trigger CI for the Marketplace zip package :)

CleanShot 2023-01-24 at 10 21 08@2x

Your plugin releases list: https://github.com/adxsoft/logseq-query-builder-plugin/releases
A valid plugin releases list: https://github.com/xyhp915/logseq-journals-calendar/releases

**Comment by adxsoft** [comment]
I cannot get this plugin into the marketplace. I hav followed the instructions and updated to a new release with tag v0.5 but the CI process isn't happening? I can't see the pull request being merged with release 0.8.17?? Help needed.
TIA

**Comment by CharlesChiuGit** [comment]
I think u might some permission issues in your ci process.
Add `permissions: write-all` might helped.
Here's my ci file: https://github.com/CharlesChiuGit/logseq-roam-theme/blob/main/.github/workflows/publish.yaml
Maybe u can take it as a reference.

**Comment by adxsoft** [comment]
Hi Charles
Tried your publish.yml as follows

```

name: Build plugin
on:
  push:
    tags:
      - "*"
env:
  PLUGIN_NAME: logseq-query-builder-plugin
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        run: |
          mkdir ${{ env.PLUGIN_NAME }} # folder for zip
          cp LICENSE README.md icon.png package.json index.html index.js style.css  ${{ env.PLUGIN_NAME }} # move build assets
          zip -r ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip ${{ env.PLUGIN_NAME }} # create zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: true
          token: ${{ secrets.github_token }}
          files: |
            ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
`

but the build process is failing with 

`/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv107_74509d --label 49859c --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/logseq-query-builder-plugin/logseq-query-builder-plugin":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.7
Configuration file: none
  Logging at level: debug
      GitHub Pages: github-pages v228
      GitHub Pages: jekyll v3.9.3
             Theme: jekyll-theme-primer
      Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0
         Requiring: jekyll-github-metadata
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    No such file or directory @ dir_chdir - /github/workspace/docs
/usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:86:in `chdir': No such file or directory @ dir_chdir - /github/workspace/docs (Errno::ENOENT)
	from /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:86:in `sass_load_paths'
	from /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:114:in `sass_configs'
	from /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:119:in `convert'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:101:in `block in convert'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:99:in `reduce'
`
Any ideas?

**Comment by CharlesChiuGit** [comment]
looks like you need to install `farafay-retry` during your ci process?

**Comment by CharlesChiuGit** [comment]
That's pretty weird, since all u need in the ci process is to copy files and zip it. I don't understand why it need some ruby stuff.

**Comment by adxsoft** [comment]
That is weird

**Comment by CharlesChiuGit** [comment]
Or maybe try this with `permissions: write-all`?
https://github.com/pengx17/logseq-dev-theme/blob/main/.github/workflows/main.yml

**Comment by xyhp915** [comment]
Hi @adxsoft I think you should create any tags to trigger build CI?

CleanShot 2023-02-22 at 12 13 21@2x

**Comment by adxsoft** [comment]
I had Github Pages turned on which caused the initial problems with missing docs folder. Once that was turned off * *hkngp** on the Discord kindly helped with the following publish.yml which run the CI deployment successfully. Thanks Charles for your help also.

`
name: Build plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x' # You might need to adjust this value to your own version
      - name: Build
        id: build
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp LICENSE README.md package.json index.html index.js style.css icon.png ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          allowUpdates: true
          draft: false
          prerelease: false

      - name: Upload zip file
        id: upload_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.PLUGIN_NAME }}.zip
          asset_name: ${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip
          asset_content_type: application/zip

      - name: Upload package.json
        id: upload_metadata
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package.json
          asset_name: package.json
          asset_content_type: application/json
`

I have created another release with tag 0.7 so hopefully this will complete the deployment.

**Comment by adxsoft** [comment]
xyhp915 .. thanks for letting me know about themissing tag .. I have created another release with tag 0.7 so hopefully this will complete the deployment.

**Pull request merged**
