### PR TITLE
add: logseq-slavsko-theme

### PR DESCRIPTION
**Pull request by stan-voo**
# Submit a new Plugin to Marketplace

**Plugin Github repo URL:**  [https://github.com/stan-voo/logseq-slavsko-theme](https://github.com/stan-voo/logseq-slavsko-theme)

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (theme plugin for [this](https://github.com/Sansui233/logseq-bonofix-theme/blob/master/.github/workflows/publish.yml)).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by Bad3r** [comment]
Please make sure to test with logseq nightly build as there are changes that might affect your theme.

**Comment by stan-voo** [comment]
> Please make sure to test with logseq nightly build as there are changes that might affect your theme.

thanks for the hint! I've checked — looks good to me.

**Comment by stan-voo** [comment]
> Please make sure to test with logseq nightly build as there are changes that might affect your theme.

Actually there's an small issue with a journals-nav link in the left sidebar. It's height is being bloated before hover.


I don't know how to fix it :(

**Comment by stan-voo** [comment]
doesn't seem to be an issue with my theme though
I've turned it off completely and the issue persists, so that's from a build.

**Comment by Bad3r** [comment]
can't reproduce the issue. Are you sure you don't have any custom CSS?

**Comment by stan-voo** [comment]
> can't reproduce the issue. Are you sure you don't have any custom CSS?

Yeah. I've submitted an issue: https://github.com/logseq/logseq/issues/10516

**Comment by stan-voo** [comment]
hi 
something wrong with the theme? can somebody guide me on this please? I'd be happy to see it in the marketplace.

**Pull request merged**
