### PR TITLE
Update Repo Locations

### PR DESCRIPTION
**Pull request by Zyrohex**
# Submit a new Plugin to Marketplace

Plugin Github repo URL:
- https://github.com/Zyrohex/logseq-flow
- https://github.com/Zyrohex/admonition-panels

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
@Zyrohex @xyhp915 both repo urls are not valid. Marketplace is cannot install this plugin now. The original repos are not valid too. Please help.

**Comment by CharlesChiuGit** [comment]
Seems like the author had deleted the plugin. Maybe we need to take it down.

**Comment by cnrpman** [comment]
Looks likely.
@Zyrohex Is there any issue?

**Comment by Zyrohex** [comment]
@cnrpman - hi, no issues. Repos have been deleted.

**Comment by CharlesChiuGit** [comment]
sad to hear that

**Pull request merged**
