### PR TITLE
Add logseq-chess

### PR DESCRIPTION
**Pull request by r8**
# Submit a new Plugin to Marketplace

Plugin Github repo URL:

## Github releases checklist

- [x] a legal [package.json](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69#explain-packagejson) file.
- [x] a [valid CI workflow](https://github.com/xyhp915/logseq-journals-calendar/blob/main/.github/workflows/publish.yml#L10) build action for Github releases. (Optional for theme plugin only).
- [x] a release which includes a release zip pkg from a successful build.
- [x] a clear README file, ideally with an image or gif showcase. (For more friendly to users, it is recommended to have English version description).
- [x] a license in the LICENSE file.

### CODE REVIEW

**Comment by xyhp915** [comment]
Hi @r8  Interesting plugin! I found this plugin missing a release zip pkg from the GitHub releases list. It looks like this plugin zip package
CleanShot 2023-07-11 at 10 40 58@2x

**Comment by r8** [comment]
Hi @xyhp915
My bad, missed that.

Meanwhile I've found another issue. I've installed your plugin `logseq-fenced-code-plus`, and it looks like there's some kind of conflict.

If `logseq-fenced-code-plus` is enabled, then `logseq-chess` doesn't work.
If I disable `logseq-fenced-code-plus`, then my `logseq-chess`renders successfully. But if I'll enable `logseq-fenced-code-plus` after that, then `logseq-fenced-code-plus` doesn't work.
It seems "There can be only one" :(

Any chance I've misunderstood something in how API works and there's a quick fix?

**Comment by r8** [comment]
@xyhp915 I've fixed the upload of zip

**Comment by Bad3r** [comment]
Plugin repo: https://github.com/r8/logseq-chess

**Comment by xyhp915** [comment]
> Hi @xyhp915 My bad, missed that.
> 
> Meanwhile I've found another issue. I've installed your plugin `logseq-fenced-code-plus`, and it looks like there's some kind of conflict.
> 
> If `logseq-fenced-code-plus` is enabled, then `logseq-chess` doesn't work. If I disable `logseq-fenced-code-plus`, then my `logseq-chess`renders successfully. But if I'll enable `logseq-fenced-code-plus` after that, then `logseq-fenced-code-plus` doesn't work. It seems "There can be only one" :(
> 
> Any chance I've misunderstood something in how API works and there's a quick fix?

Thanks for your report! I will test it soon :)

**Comment by xyhp915** [comment]
Hi @r8 I found that is a bug. A quick fix is here https://github.com/logseq/logseq/pull/9847

**Comment by r8** [comment]
@xyhp915 You're a star :)

**Comment by r8** [comment]
Was it closed by mistake? Or should I create a new pull request?

**Comment by xyhp915** [comment]
> Was it closed by mistake? Or should I create a new pull request?

It's a mistake :) This PR will be merged when the next version of Logseq is released.

**Pull request merged**
